version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - backend
  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - backend
  api:
    image: app
    build: .
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
    depends_on:
      - mongo
      - redis
    networks:
      - backend
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - REDIS_SERVER=redis
      - SERVER_URL=http://localhost:8000
networks:
  backend:
    driver: bridge
